#if !canImport(ObjectiveC)
    import XCTest

    extension Socks5HandlerTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__Socks5HandlerTests = [
            ("testSocks5DecoderWithHost", testSocks5DecoderWithHost),
            ("testSocks5DecoderWithIpConnect", testSocks5DecoderWithIpConnect),
            ("testSocks5DecoderWithMethods", testSocks5DecoderWithMethods),
            ("testSocks5DecoderWithOneMethod", testSocks5DecoderWithOneMethod),
            ("testSocks5Encoder", testSocks5Encoder),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(Socks5HandlerTests.__allTests__Socks5HandlerTests),
        ]
    }
#endif
