#if !canImport(ObjectiveC)
    import XCTest

    extension HttpProxyHandlerTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__HttpProxyHandlerTests = [
            ("testHttpConnectHandler", testHttpConnectHandler),
            ("testHttpRequestHandler", testHttpRequestHandler),
        ]
    }

    extension Socks5HandlerTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__Socks5HandlerTests = [
            ("testSocks5DecoderWithHost", testSocks5DecoderWithHost),
            ("testSocks5DecoderWithIpConnect", testSocks5DecoderWithIpConnect),
            ("testSocks5DecoderWithMethods", testSocks5DecoderWithMethods),
            ("testSocks5DecoderWithOneMethod", testSocks5DecoderWithOneMethod),
            ("testSocks5Encoder", testSocks5Encoder),
            ("testSocks5Handler", testSocks5Handler),
        ]
    }

    extension UrlParserTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__UrlParserTests = [
            ("testParseFullHttpUrl", testParseFullHttpUrl),
            ("testParsePartialHttpUrl", testParsePartialHttpUrl),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(HttpProxyHandlerTests.__allTests__HttpProxyHandlerTests),
            testCase(Socks5HandlerTests.__allTests__Socks5HandlerTests),
            testCase(UrlParserTests.__allTests__UrlParserTests),
        ]
    }
#endif
