#if !canImport(ObjectiveC)
    import XCTest

    extension Socks5HandlerTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__Socks5HandlerTests = [
            ("testSocks5DecoderWithOneMethod", testSocks5DecoderWithOneMethod),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(Socks5HandlerTests.__allTests__Socks5HandlerTests),
        ]
    }
#endif
